# Generated by Django 4.2.6 on 2023-10-27 16:58

from django.db import migrations, models
import recipe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='unit',
            field=models.CharField(max_length=50, validators=[recipe.validators.validate_unit_of_measure]),
        ),
    ]
