# Generated by Django 4.2.6 on 2023-11-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='meal',
            managers=[
            ],
        ),
    ]
