# Generated by Django 4.2.6 on 2023-11-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_alter_meal_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='prev_status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'completed'), ('e', 'expired'), ('a', 'aborted')], default='p', max_length=1),
        ),
    ]
