# Generated by Django 4.2.6 on 2023-11-02 08:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='articles',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
